### ISSUE TITLE
pass task info through the api

### ISSUE THREAD

**Issue by altmattr** [cjpappas/MacSim#8]
I need seconds remaining in particular please

**Comment by cjpappas** [comment]
I've updated the api to capture name, state, ready_time (secs), running_time (secs), elapsed_time (secs), remaining_time (secs), timed_out, score.

- Did you want me to also include nano seconds for the times?
- There are a few fields I left out because I didn't think they were too relevant to us at the moment. The full list can be found at https://github.com/osrf/vrx/blob/master/vrx_gazebo/msg/Task.msg
